# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'foldsverif.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FoldsVerifForm(object):
    def setupUi(self, FoldsVerifForm):
        FoldsVerifForm.setObjectName("FoldsVerifForm")
        FoldsVerifForm.resize(1100, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FoldsVerifForm.sizePolicy().hasHeightForWidth())
        FoldsVerifForm.setSizePolicy(sizePolicy)
        FoldsVerifForm.setMinimumSize(QtCore.QSize(1100, 850))
        FoldsVerifForm.setMaximumSize(QtCore.QSize(1100, 850))
        FoldsVerifForm.setStyleSheet("#tabsPages{\n"
"background-color:rgba(56, 64, 73, 0.8);\n"
"}\n"
"QTabWidget::pane {\n"
"    background-color:rgba(56, 64, 73, 0.8);\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab {\n"
"    background-color:rgba(95, 107, 110, 1); /* Set the desired background color for the tab buttons */\n"
"    color: white; /* Set the desired text color for the tab buttons */\n"
"font-weight:bold;\n"
"width: 140px; /* Set the desired width of the tab buttons */\n"
"height: 33px;\n"
"border-top-right-radius: 10px; /* Set the desired border radius for the top-right corner */\n"
"border-top-left-radius: 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgba(90, 255, 231, 1); /* Set the desired background color for the selected tab button */\n"
"    color: white; /* Set the desired text color for the selected tab button */\n"
"font-weight:bold;\n"
"}\n"
"#Distribution, #RocCurve, #Magnitude, #SimIndex,#FussionRegression{\n"
"background-color:rgba(56, 64, 73, 0.8);\n"
"}\n"
"QCheckBox {\n"
"    color: rgba(231, 235, 244, 1); /* Remplacez \"red\" par la couleur souhaitée */\n"
"font-size:12px;\n"
"font-weight:bold;\n"
"}\n"
"#frame_3,#frame_4,#frame_5,#frame_6,#frame_7,#frame_8,#frame_9{\n"
"background-color:rgba(47, 61, 78, 0);\n"
"}\n"
"QTabBar::tab:disabled {\n"
"    background-color: rgba(150, 150, 150, 1); /* Set the desired background color for disabled tab */\n"
"    color: rgba(200, 200, 200, 1); /* Set the desired text color for disabled tab */\n"
"}\n"
"\n"
"    \n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(FoldsVerifForm)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.workingspace = QtWidgets.QFrame(FoldsVerifForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workingspace.sizePolicy().hasHeightForWidth())
        self.workingspace.setSizePolicy(sizePolicy)
        self.workingspace.setMinimumSize(QtCore.QSize(900, 850))
        self.workingspace.setMaximumSize(QtCore.QSize(900, 850))
        self.workingspace.setStyleSheet("background-color: rgb(35, 33, 40);")
        self.workingspace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.workingspace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workingspace.setObjectName("workingspace")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.workingspace)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonspace = QtWidgets.QFrame(self.workingspace)
        self.buttonspace.setMaximumSize(QtCore.QSize(16777215, 150))
        self.buttonspace.setObjectName("buttonspace")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.buttonspace)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_21 = QtWidgets.QLabel(self.buttonspace)
        self.label_21.setMaximumSize(QtCore.QSize(150, 50))
        self.label_21.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Georgia\";\n"
"")
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.datasetcombobox = QtWidgets.QComboBox(self.buttonspace)
        self.datasetcombobox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.datasetcombobox.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/images/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::scrollbar:vertical {\n"
"    background-color: #E0E0E0;  /* Set the background color of the vertical scrollbar */\n"
"    width: 10px;                /* Set the width of the scrollbar */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::scrollbar-handle:vertical {\n"
"    background-color: #BDBDBD;  /* Set the color of the scrollbar handle */\n"
"    border-radius: 5px;         /* Add rounded corners to the scrollbar handle */\n"
"}\n"
"\n"
"QScrollBar:vertical {border: 1px solid #999999; background:white; width:10px; margin: 0px 0px 0px 0px;}\n"
"\n"
"\n"
"QScrollBar::handle:vertical {background:rgb(47, 61, 78);  min-height: 0px; border-radius: 20px}")
        self.datasetcombobox.setObjectName("datasetcombobox")
        self.datasetcombobox.addItem("")
        self.datasetcombobox.addItem("")
        self.horizontalLayout_4.addWidget(self.datasetcombobox)
        self.label_14 = QtWidgets.QLabel(self.buttonspace)
        self.label_14.setMaximumSize(QtCore.QSize(150, 50))
        self.label_14.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Georgia\";\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.foldcombobox = QtWidgets.QComboBox(self.buttonspace)
        self.foldcombobox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.foldcombobox.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: content;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/images/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::scrollbar:vertical {\n"
"    background-color: #E0E0E0;  /* Set the background color of the vertical scrollbar */\n"
"    width: 10px;                /* Set the width of the scrollbar */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::scrollbar-handle:vertical {\n"
"    background-color: #BDBDBD;  /* Set the color of the scrollbar handle */\n"
"    border-radius: 5px;         /* Add rounded corners to the scrollbar handle */\n"
"}\n"
"\n"
"QScrollBar:vertical {border: 1px solid #999999; background:white; width:10px; margin: 0px 0px 0px 0px;}\n"
"\n"
"\n"
"QScrollBar::handle:vertical {background:rgb(47, 61, 78);  min-height: 0px; border-radius: 20px}")
        self.foldcombobox.setObjectName("foldcombobox")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.foldcombobox.addItem("")
        self.horizontalLayout_4.addWidget(self.foldcombobox)
        self.apply_folds_verif_btn = QtWidgets.QPushButton(self.buttonspace)
        self.apply_folds_verif_btn.setEnabled(False)
        self.apply_folds_verif_btn.setMaximumSize(QtCore.QSize(200, 40))
        self.apply_folds_verif_btn.setStyleSheet("background-color: rgb(170, 170, 170);border-radius: 10px;color:rgb(255, 255, 255);\n"
"font: 75 10pt \"Georgia\";")
        self.apply_folds_verif_btn.setObjectName("apply_folds_verif_btn")
        self.horizontalLayout_4.addWidget(self.apply_folds_verif_btn)
        self.verticalLayout.addWidget(self.buttonspace)
        self.imagespace = QtWidgets.QFrame(self.workingspace)
        self.imagespace.setObjectName("imagespace")
        self.tabsPages = QtWidgets.QTabWidget(self.imagespace)
        self.tabsPages.setGeometry(QtCore.QRect(20, 10, 850, 452))
        self.tabsPages.setMinimumSize(QtCore.QSize(711, 0))
        self.tabsPages.setMaximumSize(QtCore.QSize(870, 16777215))
        self.tabsPages.setStyleSheet("QTabWidget::pane {\n"
"    background-color:rgba(56, 64, 73, 0.8); \n"
"}")
        self.tabsPages.setMovable(True)
        self.tabsPages.setObjectName("tabsPages")
        self.distribution = QtWidgets.QWidget()
        self.distribution.setObjectName("distribution")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.distribution)
        self.gridLayout_2.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dist_plot = QtWidgets.QFrame(self.distribution)
        self.dist_plot.setMinimumSize(QtCore.QSize(708, 380))
        self.dist_plot.setMaximumSize(QtCore.QSize(865, 480))
        self.dist_plot.setStyleSheet("background-color:rgb(83, 83, 83);\n"
"border-radius: 10px;")
        self.dist_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dist_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dist_plot.setObjectName("dist_plot")
        self.label_15 = QtWidgets.QLabel(self.dist_plot)
        self.label_15.setGeometry(QtCore.QRect(220, 120, 400, 150))
        self.label_15.setMinimumSize(QtCore.QSize(400, 150))
        self.label_15.setMaximumSize(QtCore.QSize(400, 150))
        self.label_15.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.dist_plot, 0, 0, 1, 1)
        self.tabsPages.addTab(self.distribution, "")
        self.roccurve = QtWidgets.QWidget()
        self.roccurve.setObjectName("roccurve")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.roccurve)
        self.gridLayout_8.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.roccurve_plot = QtWidgets.QFrame(self.roccurve)
        self.roccurve_plot.setMinimumSize(QtCore.QSize(708, 380))
        self.roccurve_plot.setMaximumSize(QtCore.QSize(865, 480))
        self.roccurve_plot.setStyleSheet("background-color:rgb(83, 83, 83);\n"
"border-radius: 10px;")
        self.roccurve_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roccurve_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roccurve_plot.setObjectName("roccurve_plot")
        self.label_16 = QtWidgets.QLabel(self.roccurve_plot)
        self.label_16.setGeometry(QtCore.QRect(220, 120, 400, 150))
        self.label_16.setMinimumSize(QtCore.QSize(400, 150))
        self.label_16.setMaximumSize(QtCore.QSize(400, 150))
        self.label_16.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.roccurve_plot, 0, 0, 1, 1)
        self.tabsPages.addTab(self.roccurve, "")
        self.magnitude = QtWidgets.QWidget()
        self.magnitude.setObjectName("magnitude")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.magnitude)
        self.gridLayout_9.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.magnitudeplot = QtWidgets.QFrame(self.magnitude)
        self.magnitudeplot.setMinimumSize(QtCore.QSize(708, 380))
        self.magnitudeplot.setMaximumSize(QtCore.QSize(865, 480))
        self.magnitudeplot.setStyleSheet("background-color:rgb(83, 83, 83);\n"
"border-radius: 10px;")
        self.magnitudeplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.magnitudeplot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.magnitudeplot.setObjectName("magnitudeplot")
        self.label_18 = QtWidgets.QLabel(self.magnitudeplot)
        self.label_18.setGeometry(QtCore.QRect(220, 120, 400, 150))
        self.label_18.setMinimumSize(QtCore.QSize(400, 150))
        self.label_18.setMaximumSize(QtCore.QSize(400, 150))
        self.label_18.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.magnitudeplot, 0, 0, 1, 1)
        self.tabsPages.addTab(self.magnitude, "")
        self.simindex = QtWidgets.QWidget()
        self.simindex.setObjectName("simindex")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.simindex)
        self.gridLayout_10.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.simindexplot = QtWidgets.QFrame(self.simindex)
        self.simindexplot.setMinimumSize(QtCore.QSize(708, 380))
        self.simindexplot.setMaximumSize(QtCore.QSize(865, 480))
        self.simindexplot.setStyleSheet("background-color:rgb(83, 83, 83);\n"
"border-radius: 10px;")
        self.simindexplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.simindexplot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.simindexplot.setObjectName("simindexplot")
        self.label_19 = QtWidgets.QLabel(self.simindexplot)
        self.label_19.setGeometry(QtCore.QRect(220, 120, 400, 150))
        self.label_19.setMinimumSize(QtCore.QSize(400, 150))
        self.label_19.setMaximumSize(QtCore.QSize(400, 150))
        self.label_19.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.simindexplot, 0, 0, 1, 1)
        self.tabsPages.addTab(self.simindex, "")
        self.fusionregression = QtWidgets.QWidget()
        self.fusionregression.setEnabled(True)
        self.fusionregression.setObjectName("fusionregression")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.fusionregression)
        self.gridLayout_11.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.fusionregressionplot = QtWidgets.QFrame(self.fusionregression)
        self.fusionregressionplot.setMinimumSize(QtCore.QSize(708, 380))
        self.fusionregressionplot.setMaximumSize(QtCore.QSize(865, 480))
        self.fusionregressionplot.setStyleSheet("background-color:rgb(83, 83, 83);\n"
"border-radius: 10px;")
        self.fusionregressionplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fusionregressionplot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fusionregressionplot.setObjectName("fusionregressionplot")
        self.label_20 = QtWidgets.QLabel(self.fusionregressionplot)
        self.label_20.setGeometry(QtCore.QRect(220, 120, 400, 150))
        self.label_20.setMinimumSize(QtCore.QSize(400, 150))
        self.label_20.setMaximumSize(QtCore.QSize(400, 150))
        self.label_20.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.fusionregressionplot, 0, 0, 1, 1)
        self.tabsPages.addTab(self.fusionregression, "")
        self.verticalLayout.addWidget(self.imagespace)
        self.resultspace = QtWidgets.QFrame(self.workingspace)
        self.resultspace.setMinimumSize(QtCore.QSize(900, 200))
        self.resultspace.setMaximumSize(QtCore.QSize(900, 200))
        self.resultspace.setStyleSheet("background-color: rgb(47, 61, 78);")
        self.resultspace.setObjectName("resultspace")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.resultspace)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.resultspace)
        self.label_13.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/icons/details.png"))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.result = QtWidgets.QLabel(self.resultspace)
        self.result.setMaximumSize(QtCore.QSize(16777215, 50))
        self.result.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.horizontalLayout_5.addWidget(self.result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalFrame = QtWidgets.QFrame(self.resultspace)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_3.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Georgia\";\n"
"padding-top:20px")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.FR = QtWidgets.QLabel(self.horizontalFrame)
        self.FR.setMaximumSize(QtCore.QSize(16777215, 50))
        self.FR.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.FR.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FR.setObjectName("FR")
        self.horizontalLayout_6.addWidget(self.FR)
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_4.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Georgia\";\n"
"padding-top:20px")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.FA = QtWidgets.QLabel(self.horizontalFrame)
        self.FA.setMaximumSize(QtCore.QSize(16777215, 50))
        self.FA.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.FA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FA.setObjectName("FA")
        self.horizontalLayout_6.addWidget(self.FA)
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_5.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Georgia\";\n"
"padding-top:20px")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.accuracy = QtWidgets.QLabel(self.horizontalFrame)
        self.accuracy.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.accuracy.setObjectName("accuracy")
        self.horizontalLayout_6.addWidget(self.accuracy)
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_7.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Georgia\";\n"
"padding-top:20px")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.threshold = QtWidgets.QLabel(self.horizontalFrame)
        self.threshold.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Georgia\";\n"
"padding-top:20px")
        self.threshold.setObjectName("threshold")
        self.horizontalLayout_6.addWidget(self.threshold)
        self.verticalLayout_3.addWidget(self.horizontalFrame)
        self.verticalLayout.addWidget(self.resultspace)
        self.horizontalLayout_2.addWidget(self.workingspace)
        self.rightmenubar = QtWidgets.QFrame(FoldsVerifForm)
        self.rightmenubar.setMinimumSize(QtCore.QSize(200, 850))
        self.rightmenubar.setMaximumSize(QtCore.QSize(200, 850))
        self.rightmenubar.setStyleSheet("background-color: rgb(47, 61, 78);")
        self.rightmenubar.setObjectName("rightmenubar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightmenubar)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.rightmenubar)
        self.frame_2.setMaximumSize(QtCore.QSize(200, 80))
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setMinimumSize(QtCore.QSize(80, 80))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/icons/images/reglages.png"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(120, 80))
        self.label_11.setMaximumSize(QtCore.QSize(120, 80))
        self.label_11.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Georgia\";\n"
"padding-right:20px")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.recognitionlabem = QtWidgets.QLabel(self.rightmenubar)
        self.recognitionlabem.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.recognitionlabem.setAlignment(QtCore.Qt.AlignCenter)
        self.recognitionlabem.setObjectName("recognitionlabem")
        self.verticalLayout_2.addWidget(self.recognitionlabem)
        self.frame_4 = QtWidgets.QFrame(self.rightmenubar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(60, 50))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.recognitionmodel = QtWidgets.QComboBox(self.frame_4)
        self.recognitionmodel.setEnabled(True)
        self.recognitionmodel.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/images/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }")
        self.recognitionmodel.setObjectName("recognitionmodel")
        self.recognitionmodel.addItem("")
        self.recognitionmodel.addItem("")
        self.recognitionmodel.addItem("")
        self.horizontalLayout.addWidget(self.recognitionmodel)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.label_10 = QtWidgets.QLabel(self.rightmenubar)
        self.label_10.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.classic_checkbox = QtWidgets.QCheckBox(self.rightmenubar)
        self.classic_checkbox.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.classic_checkbox.setObjectName("classic_checkbox")
        self.verticalLayout_2.addWidget(self.classic_checkbox)
        self.rest_model_classic = QtWidgets.QComboBox(self.rightmenubar)
        self.rest_model_classic.setEnabled(False)
        self.rest_model_classic.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/images/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }")
        self.rest_model_classic.setObjectName("rest_model_classic")
        self.rest_model_classic.addItem("")
        self.rest_model_classic.addItem("")
        self.verticalLayout_2.addWidget(self.rest_model_classic)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.advancedwidget = QtWidgets.QWidget(self.rightmenubar)
        self.advancedwidget.setObjectName("advancedwidget")
        self.advancedlayout = QtWidgets.QVBoxLayout(self.advancedwidget)
        self.advancedlayout.setObjectName("advancedlayout")
        self.advancedcheckbox = QtWidgets.QCheckBox(self.advancedwidget)
        self.advancedcheckbox.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.advancedcheckbox.setObjectName("advancedcheckbox")
        self.advancedlayout.addWidget(self.advancedcheckbox)
        self.typefusioncombobox = QtWidgets.QComboBox(self.advancedwidget)
        self.typefusioncombobox.setEnabled(False)
        self.typefusioncombobox.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/images/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }\n"
"")
        self.typefusioncombobox.setObjectName("typefusioncombobox")
        self.typefusioncombobox.addItem("")
        self.typefusioncombobox.addItem("")
        self.typefusioncombobox.addItem("")
        self.advancedlayout.addWidget(self.typefusioncombobox)
        self.label = QtWidgets.QLabel(self.advancedwidget)
        self.label.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"Georgia\";\n"
"padding-top:20px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.advancedlayout.addWidget(self.label)
        self.frame_3 = QtWidgets.QFrame(self.advancedwidget)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_10.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(60, 50))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.featurelevelcombobox = QtWidgets.QComboBox(self.frame_3)
        self.featurelevelcombobox.setEnabled(False)
        self.featurelevelcombobox.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/images/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }")
        self.featurelevelcombobox.setObjectName("featurelevelcombobox")
        self.featurelevelcombobox.addItem("")
        self.featurelevelcombobox.addItem("")
        self.featurelevelcombobox.addItem("")
        self.featurelevelcombobox.addItem("")
        self.horizontalLayout_10.addWidget(self.featurelevelcombobox)
        self.advancedlayout.addWidget(self.frame_3)
        self.scorelevellabel = QtWidgets.QLabel(self.advancedwidget)
        self.scorelevellabel.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.scorelevellabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scorelevellabel.setObjectName("scorelevellabel")
        self.advancedlayout.addWidget(self.scorelevellabel)
        self.scorelev = QtWidgets.QFrame(self.advancedwidget)
        self.scorelev.setObjectName("scorelev")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.scorelev)
        self.horizontalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.scorelev)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(60, 30))
        self.label_17.setMaximumSize(QtCore.QSize(60, 50))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.scorelevelcombobox = QtWidgets.QComboBox(self.scorelev)
        self.scorelevelcombobox.setEnabled(False)
        self.scorelevelcombobox.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/images/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }\n"
"")
        self.scorelevelcombobox.setObjectName("scorelevelcombobox")
        self.scorelevelcombobox.addItem("")
        self.scorelevelcombobox.addItem("")
        self.scorelevelcombobox.addItem("")
        self.horizontalLayout_14.addWidget(self.scorelevelcombobox)
        self.advancedlayout.addWidget(self.scorelev)
        self.verticalLayout_2.addWidget(self.advancedwidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.rightmenubar)

        self.retranslateUi(FoldsVerifForm)
        self.tabsPages.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(FoldsVerifForm)

    def retranslateUi(self, FoldsVerifForm):
        _translate = QtCore.QCoreApplication.translate
        FoldsVerifForm.setWindowTitle(_translate("FoldsVerifForm", "Form"))
        self.label_21.setText(_translate("FoldsVerifForm", "Choose your dataset: "))
        self.datasetcombobox.setItemText(0, _translate("FoldsVerifForm", "LFW"))
        self.datasetcombobox.setItemText(1, _translate("FoldsVerifForm", "XQLFW"))
        self.label_14.setText(_translate("FoldsVerifForm", "Choose your folder: "))
        self.foldcombobox.setItemText(0, _translate("FoldsVerifForm", "ALL"))
        self.foldcombobox.setItemText(1, _translate("FoldsVerifForm", "0"))
        self.foldcombobox.setItemText(2, _translate("FoldsVerifForm", "1"))
        self.foldcombobox.setItemText(3, _translate("FoldsVerifForm", "2"))
        self.foldcombobox.setItemText(4, _translate("FoldsVerifForm", "3"))
        self.foldcombobox.setItemText(5, _translate("FoldsVerifForm", "4"))
        self.foldcombobox.setItemText(6, _translate("FoldsVerifForm", "5"))
        self.foldcombobox.setItemText(7, _translate("FoldsVerifForm", "6"))
        self.foldcombobox.setItemText(8, _translate("FoldsVerifForm", "7"))
        self.foldcombobox.setItemText(9, _translate("FoldsVerifForm", "8"))
        self.foldcombobox.setItemText(10, _translate("FoldsVerifForm", "9"))
        self.apply_folds_verif_btn.setText(_translate("FoldsVerifForm", "apply"))
        self.label_15.setText(_translate("FoldsVerifForm", "Click Apply!\n"
" Distribution plot will appear here!"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.distribution), _translate("FoldsVerifForm", "Distribution"))
        self.label_16.setText(_translate("FoldsVerifForm", "Click Apply!\n"
" Roc Curve plot will appear here!"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.roccurve), _translate("FoldsVerifForm", "Roc Curve"))
        self.label_18.setText(_translate("FoldsVerifForm", "Click Apply!\n"
" Magnitude plot will appear here!"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.magnitude), _translate("FoldsVerifForm", "Magnitude"))
        self.label_19.setText(_translate("FoldsVerifForm", "Click Apply!\n"
" Similarity index plot will appear here!"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.simindex), _translate("FoldsVerifForm", "Sim Index"))
        self.label_20.setText(_translate("FoldsVerifForm", "Click Apply!\n"
" Scores scatter plots will appear here!"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.fusionregression), _translate("FoldsVerifForm", "Fusion Regression"))
        self.result.setText(_translate("FoldsVerifForm", "Details"))
        self.label_3.setText(_translate("FoldsVerifForm", "False rejection:"))
        self.FR.setText(_translate("FoldsVerifForm", "-"))
        self.label_4.setText(_translate("FoldsVerifForm", "False Acceptance:"))
        self.FA.setText(_translate("FoldsVerifForm", "-"))
        self.label_5.setText(_translate("FoldsVerifForm", "Accuracy:"))
        self.accuracy.setText(_translate("FoldsVerifForm", "-"))
        self.label_7.setText(_translate("FoldsVerifForm", "Threshold:"))
        self.threshold.setText(_translate("FoldsVerifForm", "-"))
        self.label_11.setText(_translate("FoldsVerifForm", "Settings"))
        self.recognitionlabem.setText(_translate("FoldsVerifForm", "Recognition"))
        self.label_2.setText(_translate("FoldsVerifForm", "model"))
        self.recognitionmodel.setItemText(0, _translate("FoldsVerifForm", "AdaFace"))
        self.recognitionmodel.setItemText(1, _translate("FoldsVerifForm", "MagFace"))
        self.recognitionmodel.setItemText(2, _translate("FoldsVerifForm", "ArcFace"))
        self.label_10.setText(_translate("FoldsVerifForm", "Restoration"))
        self.classic_checkbox.setText(_translate("FoldsVerifForm", "Classical"))
        self.rest_model_classic.setItemText(0, _translate("FoldsVerifForm", "GFPGAN"))
        self.rest_model_classic.setItemText(1, _translate("FoldsVerifForm", "GPEN"))
        self.advancedcheckbox.setText(_translate("FoldsVerifForm", "Advanced"))
        self.typefusioncombobox.setItemText(0, _translate("FoldsVerifForm", "feature fusion"))
        self.typefusioncombobox.setItemText(1, _translate("FoldsVerifForm", "score fusion"))
        self.typefusioncombobox.setItemText(2, _translate("FoldsVerifForm", "hybrid fusion"))
        self.label.setText(_translate("FoldsVerifForm", "feature level fusion"))
        self.label_12.setText(_translate("FoldsVerifForm", "models"))
        self.featurelevelcombobox.setItemText(0, _translate("FoldsVerifForm", "GPEN_SGPN"))
        self.featurelevelcombobox.setItemText(1, _translate("FoldsVerifForm", "GPEN_GFPGAN"))
        self.featurelevelcombobox.setItemText(2, _translate("FoldsVerifForm", "SGPN_GFPGAN"))
        self.featurelevelcombobox.setItemText(3, _translate("FoldsVerifForm", "ALL"))
        self.scorelevellabel.setText(_translate("FoldsVerifForm", "score level fusion"))
        self.label_17.setText(_translate("FoldsVerifForm", "models"))
        self.scorelevelcombobox.setItemText(0, _translate("FoldsVerifForm", "GPEN_GFPGAN"))
        self.scorelevelcombobox.setItemText(1, _translate("FoldsVerifForm", "GPEN_SGPN"))
        self.scorelevelcombobox.setItemText(2, _translate("FoldsVerifForm", "SGPN_GFPGAN"))
import ressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FoldsVerifForm = QtWidgets.QWidget()
    ui = Ui_FoldsVerifForm()
    ui.setupUi(FoldsVerifForm)
    FoldsVerifForm.show()
    sys.exit(app.exec_())
