# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pairsverif.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PairsVerifForm(object):
    def setupUi(self, PairsVerifForm):
        PairsVerifForm.setObjectName("PairsVerifForm")
        PairsVerifForm.resize(1100, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PairsVerifForm.sizePolicy().hasHeightForWidth())
        PairsVerifForm.setSizePolicy(sizePolicy)
        PairsVerifForm.setMinimumSize(QtCore.QSize(600, 450))
        PairsVerifForm.setMaximumSize(QtCore.QSize(1100, 850))
        self.workingspace = QtWidgets.QFrame(PairsVerifForm)
        self.workingspace.setGeometry(QtCore.QRect(0, 0, 900, 850))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workingspace.sizePolicy().hasHeightForWidth())
        self.workingspace.setSizePolicy(sizePolicy)
        self.workingspace.setMinimumSize(QtCore.QSize(650, 450))
        self.workingspace.setMaximumSize(QtCore.QSize(900, 850))
        self.workingspace.setStyleSheet("background-color: rgb(35, 33, 40);")
        self.workingspace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.workingspace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workingspace.setObjectName("workingspace")
        self.apply_pairs_verif_btn = QtWidgets.QPushButton(self.workingspace)
        self.apply_pairs_verif_btn.setEnabled(True)
        self.apply_pairs_verif_btn.setGeometry(QtCore.QRect(380, 200, 200, 40))
        self.apply_pairs_verif_btn.setMaximumSize(QtCore.QSize(200, 40))
        self.apply_pairs_verif_btn.setStyleSheet("background-color: rgb(170, 170, 170);border-radius: 10px;color:rgb(255, 255, 255);\n"
"font: 75 10pt \"Georgia\";")
        self.apply_pairs_verif_btn.setObjectName("apply_pairs_verif_btn")
        self.accuracy = QtWidgets.QLabel(self.workingspace)
        self.accuracy.setGeometry(QtCore.QRect(150, 370, 191, 81))
        self.accuracy.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.accuracy.setAlignment(QtCore.Qt.AlignCenter)
        self.accuracy.setObjectName("accuracy")
        self.threshold = QtWidgets.QLabel(self.workingspace)
        self.threshold.setGeometry(QtCore.QRect(530, 360, 191, 81))
        self.threshold.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold.setObjectName("threshold")
        self.menuscroll = QtWidgets.QScrollArea(PairsVerifForm)
        self.menuscroll.setGeometry(QtCore.QRect(900, 0, 200, 850))
        self.menuscroll.setMinimumSize(QtCore.QSize(100, 450))
        self.menuscroll.setMaximumSize(QtCore.QSize(200, 850))
        self.menuscroll.setWidgetResizable(True)
        self.menuscroll.setObjectName("menuscroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 198, 848))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(100, 450))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(200, 850))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.rightmenuverification = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.rightmenuverification.setGeometry(QtCore.QRect(0, 0, 200, 1000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightmenuverification.sizePolicy().hasHeightForWidth())
        self.rightmenuverification.setSizePolicy(sizePolicy)
        self.rightmenuverification.setMinimumSize(QtCore.QSize(100, 500))
        self.rightmenuverification.setMaximumSize(QtCore.QSize(200, 1000))
        self.rightmenuverification.setStyleSheet("background-color: rgb(36, 40, 59);")
        self.rightmenuverification.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightmenuverification.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightmenuverification.setObjectName("rightmenuverification")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.rightmenuverification)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.rightmenuverification)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(200, 80))
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setMinimumSize(QtCore.QSize(80, 80))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/icons/images/reglages.png"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(120, 80))
        self.label_11.setMaximumSize(QtCore.QSize(120, 80))
        self.label_11.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Georgia\";\n"
"padding-right:20px")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.detectcomboBox_2 = QtWidgets.QComboBox(self.frame)
        self.detectcomboBox_2.setEnabled(False)
        self.detectcomboBox_2.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }")
        self.detectcomboBox_2.setObjectName("detectcomboBox_2")
        self.detectcomboBox_2.addItem("")
        self.detectcomboBox_2.addItem("")
        self.detectcomboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.detectcomboBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.noisecheckBox = QtWidgets.QCheckBox(self.frame)
        self.noisecheckBox.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.noisecheckBox.setObjectName("noisecheckBox")
        self.verticalLayout_2.addWidget(self.noisecheckBox)
        self.noisecheckBox_2 = QtWidgets.QCheckBox(self.frame)
        self.noisecheckBox_2.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.noisecheckBox_2.setObjectName("noisecheckBox_2")
        self.verticalLayout_2.addWidget(self.noisecheckBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.detectcheckBox = QtWidgets.QCheckBox(self.frame)
        self.detectcheckBox.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.detectcheckBox.setObjectName("detectcheckBox")
        self.verticalLayout_2.addWidget(self.detectcheckBox)
        self.blurcheckbox = QtWidgets.QCheckBox(self.frame)
        self.blurcheckbox.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.blurcheckbox.setObjectName("blurcheckbox")
        self.verticalLayout_2.addWidget(self.blurcheckbox)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(60, 50))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.detectcomboBox_3 = QtWidgets.QComboBox(self.frame_3)
        self.detectcomboBox_3.setEnabled(False)
        self.detectcomboBox_3.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }")
        self.detectcomboBox_3.setObjectName("detectcomboBox_3")
        self.detectcomboBox_3.addItem("")
        self.detectcomboBox_3.addItem("")
        self.horizontalLayout_10.addWidget(self.detectcomboBox_3)
        self.verticalLayout_2.addWidget(self.frame_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(60, 30))
        self.label_17.setMaximumSize(QtCore.QSize(60, 50))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.stdnoise_2 = QtWidgets.QLineEdit(self.frame_7)
        self.stdnoise_2.setEnabled(False)
        self.stdnoise_2.setMaximumSize(QtCore.QSize(100, 30))
        self.stdnoise_2.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:10px;\n"
"")
        self.stdnoise_2.setMaxLength(6)
        self.stdnoise_2.setObjectName("stdnoise_2")
        self.horizontalLayout_14.addWidget(self.stdnoise_2)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setMinimumSize(QtCore.QSize(0, 30))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.lowresvalue_2 = QtWidgets.QLineEdit(self.frame_6)
        self.lowresvalue_2.setEnabled(False)
        self.lowresvalue_2.setMinimumSize(QtCore.QSize(100, 30))
        self.lowresvalue_2.setMaximumSize(QtCore.QSize(100, 30))
        self.lowresvalue_2.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:10px;\n"
"")
        self.lowresvalue_2.setInputMask("")
        self.lowresvalue_2.setMaxLength(4)
        self.lowresvalue_2.setObjectName("lowresvalue_2")
        self.horizontalLayout_13.addWidget(self.lowresvalue_2)
        self.verticalLayout_2.addWidget(self.frame_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 230, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMaximumSize(QtCore.QSize(60, 50))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.meannoise_2 = QtWidgets.QLineEdit(self.frame_5)
        self.meannoise_2.setEnabled(False)
        self.meannoise_2.setMinimumSize(QtCore.QSize(100, 30))
        self.meannoise_2.setMaximumSize(QtCore.QSize(100, 30))
        self.meannoise_2.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:10px;\n"
"")
        self.meannoise_2.setMaxLength(6)
        self.meannoise_2.setObjectName("meannoise_2")
        self.horizontalLayout_12.addWidget(self.meannoise_2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.compressioncheckbox = QtWidgets.QCheckBox(self.frame)
        self.compressioncheckbox.setEnabled(True)
        self.compressioncheckbox.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px\n"
"")
        self.compressioncheckbox.setCheckable(True)
        self.compressioncheckbox.setObjectName("compressioncheckbox")
        self.verticalLayout_2.addWidget(self.compressioncheckbox)
        self.detectcomboBox = QtWidgets.QComboBox(self.frame)
        self.detectcomboBox.setEnabled(False)
        self.detectcomboBox.setStyleSheet(" QComboBox {\n"
"        background-color: white;\n"
"        font: 10pt \"Georgia\";\n"
"        padding-bottom: 8px;\n"
"        padding-left: 5px;\n"
"        border-radius: 10px;\n"
"        align:justify\n"
"    }\n"
"    \n"
"    QComboBox::down-arrow {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: bottom right;\n"
"        border-radius: 10px;\n"
"        text-align: center;\n"
"        image: url(:/icons/fleche-vers-le-bas.png);\n"
"        border:none\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView::item:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(90, 255, 231, 255), stop:1 rgba(21, 205, 202, 255));\n"
"        color: white;\n"
"    }")
        self.detectcomboBox.setObjectName("detectcomboBox")
        self.detectcomboBox.addItem("")
        self.detectcomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.detectcomboBox)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.compressionvalue_2 = QtWidgets.QLineEdit(self.frame_4)
        self.compressionvalue_2.setEnabled(False)
        self.compressionvalue_2.setMaximumSize(QtCore.QSize(100, 30))
        self.compressionvalue_2.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:10px;")
        self.compressionvalue_2.setObjectName("compressionvalue_2")
        self.horizontalLayout_11.addWidget(self.compressionvalue_2)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.lrcheckbox = QtWidgets.QCheckBox(self.frame)
        self.lrcheckbox.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Georgia\";\n"
"padding-top:20px")
        self.lrcheckbox.setObjectName("lrcheckbox")
        self.verticalLayout_2.addWidget(self.lrcheckbox)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame)
        self.menuscroll.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(PairsVerifForm)
        QtCore.QMetaObject.connectSlotsByName(PairsVerifForm)

    def retranslateUi(self, PairsVerifForm):
        _translate = QtCore.QCoreApplication.translate
        PairsVerifForm.setWindowTitle(_translate("PairsVerifForm", "Form"))
        self.apply_pairs_verif_btn.setText(_translate("PairsVerifForm", "apply"))
        self.accuracy.setText(_translate("PairsVerifForm", "acc"))
        self.threshold.setText(_translate("PairsVerifForm", "threshold"))
        self.label_11.setText(_translate("PairsVerifForm", "Settings"))
        self.label_15.setText(_translate("PairsVerifForm", "Model"))
        self.detectcomboBox_2.setItemText(0, _translate("PairsVerifForm", "AdaFace"))
        self.detectcomboBox_2.setItemText(1, _translate("PairsVerifForm", "MagFace"))
        self.detectcomboBox_2.setItemText(2, _translate("PairsVerifForm", "ArcFace"))
        self.label_18.setText(_translate("PairsVerifForm", "Preprocessing"))
        self.noisecheckBox.setText(_translate("PairsVerifForm", "Alignement"))
        self.noisecheckBox_2.setText(_translate("PairsVerifForm", "Crop"))
        self.label_10.setText(_translate("PairsVerifForm", "Restoration"))
        self.detectcheckBox.setText(_translate("PairsVerifForm", "Classical"))
        self.blurcheckbox.setText(_translate("PairsVerifForm", "Advanced"))
        self.label_12.setText(_translate("PairsVerifForm", "levels"))
        self.detectcomboBox_3.setItemText(0, _translate("PairsVerifForm", "1"))
        self.detectcomboBox_3.setItemText(1, _translate("PairsVerifForm", "2"))
        self.label_17.setText(_translate("PairsVerifForm", "std"))
        self.label_16.setText(_translate("PairsVerifForm", "scale"))
        self.label_14.setText(_translate("PairsVerifForm", "mean"))
        self.compressioncheckbox.setText(_translate("PairsVerifForm", "Compression"))
        self.detectcomboBox.setItemText(0, _translate("PairsVerifForm", "RetinaFace"))
        self.detectcomboBox.setItemText(1, _translate("PairsVerifForm", "MTCNN"))
        self.label_13.setText(_translate("PairsVerifForm", "quality"))
        self.lrcheckbox.setText(_translate("PairsVerifForm", "Low Resolution"))
        self.label.setText(_translate("PairsVerifForm", "TextLabel"))
import ressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PairsVerifForm = QtWidgets.QWidget()
    ui = Ui_PairsVerifForm()
    ui.setupUi(PairsVerifForm)
    PairsVerifForm.show()
    sys.exit(app.exec_())
